Enterprise-CMCS/mac-fc-github-actions-runner-aws

README.md
Updating the README to include the details needed for the IAM user policy and AWS permissions so we can minimize linking out to other systems.
=> Adding IAM permissions details to README

.github/workflows/docker-build.yml, README.md, Usage.md, build.sh, entrypoint.sh
The main code change is just in the `build.sh` and `entrypoint.sh` to use uuidgen to create a name for each runner so that there are no naming collisions when multiple runners are provisioned.
Added a `Usage.md` file to add documentation surrounding the usage of this module. The mac-fc-infra/gha-test branch was used to test the workflow described in this documentation.
=> Generate Unique IDs for Each Runner and Add Documentation

.github/workflows/dependabot.yml, .github/workflows/update-actions-runner.yml, Dockerfile, README.md, Usage.md
Includes:
- Major fix to runner provisioning workflow - no longer necessary to provide a task-definition.json. Instead, use the AWS CLI tool to pull it down:
```
aws ecs describe-task-definition \
--task-definition ${{ env.TASK_DEFINITION }} \
--query taskDefinition > task-definition.json
```
We are still going to include the `amazon-ecs-render-task-definition@v1` step in the workflow so that ADOs can choose a specific image if they would like. Also reflected this change in the `Usage.md` file
- Updates to README to reflect the permissions change necessary to make the above happen. Specifically, we need `"ecs:DescribeTaskDefinition"` to be on `"Resource": "*"` instead our cluster and service
- Introduce dependabot for triggering docker image updates
=> Update to task-definition workflow and introducing dependabot

.github/workflows/docker-build.yml, kube-manifest.yml
This gets us to a state where we can hook up a runner to this repo, test it's registered and online using k8s in github actions.
=> Testing with kind/k8s

.github/workflows/docker-build.yml, .github/workflows/runner-test.yml
Add's in a new workflow that targets a self-hosted runner. This workflow is triggered by our main build workflow that spins up a runner in k8s/kind so we can test our runner image and make sure it will run a job successfully.
=> Try to call out to a separate workflow that uses self-hosted runner

.github/dependabot.yml
This should pull in PRs to update things like setup-kind and other upstream actions. I also dropped the open pull request limit to reduce dependency noise.
=> Configure dependabot to update github actions versions

.github/workflows/docker-build.yml
This changes builds for new runner images to be stored in a central ECR that allows read access from within the CMS AWS Organization. A follow up PR will me made to remove the ECR repository definitions in this repo in favor of a more global ECR.
=> Switch to ECR with CMS Org read access

README.md, cloudwatch.tf, ecs.tf, variables.tf
- adds cloudwatch logs to the module itself, with the number of days for retention an optional parameter and a lifecycle policy to prevent the logs groups from being destroyed
- adds desired_count to ignore_changes lifecycle policy for ECS
- updates to documentation to more accurately reflect how the module works as well as additions being made in this PR
=> Updating parameters, putting lifecycle policies in place, and adding cloudwatch logging

.github/workflows/docker-build.yml, README.md, cloudwatch.tf, ecs.tf, variables.tf
This updates the naming scheme for resources so that this module can be used for multiple repositories within the same AWS account.
This PR generates a hash using a static namespace and string constructed from Env-OrgName-RepoName. This convention was used to help eliminate possible conflicts in the future if different Github orgs have conflicting repo names (or forks) that end up being provisioned in the same AWS account, while also limiting the maximum characters in the name of an AWS resource (the limit of which varies by AWS resources). This implementation was tested in a deployment within a private repo and test AWS account.
Additionally, this PR removes the ability to pass in an existing ECS cluster and forces the creation of one using the unique naming convention outlined above. …
=> Address naming collision for many repos to one AWS deploy

README.md
Clarifying the expected naming scheme for the github token in AWS Secrets.
=> clarify AWS Secrets naming requirement

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, container-definitions.tpl, ecs.tf, variables.tf
Ishmael asked that the CPU and memory parameters for the task and container be overridable variables. His team's use case requires a lot more of both to execute successfully.
=> Add variables for task and container CPU and memory

ecs.tf, variables.tf
Ishmeal needs this so MACPRO can publish to their own ECR.
=> Add ecr_repository_arns variable

.github/workflows/docker-build.yml, entrypoint.sh
Turns out that the ROBOT_MAC_FC_TOKEN set up by the Truss team is not configured in Dependabot secrets, so CI was failing for those jobs.  We don't know the login info for the old robot user, so for the time being we can use one of my personal tokens (set to expire in 30 days) while we work on getting a new robot user.
Also adds error handling for the API call to GitHub to get the token used to register runners.  I did this because I forgot to configure SSO for my PAT and the script that sets up the runners was failing without a helpful error. 
Testing: 
I ran the image locally with a valid/invalid token to test the branching logic and error messages in `entrypoint.sh`
=> Use personal token and add error handling

.github/workflows/update-actions-runner.yml
I noticed that the commits created by this workflow had the author and email set incorrectly (see [example commit](https://github.com/CMSgov/github-actions-runner-aws/pull/89/commits/7debc5441f8e84927318705e5babf519d403be0c))
I removed an unnecessary setup step from the workflow in the process of fixing this.
Testing: 
I rand the workflow and created a PR, which you can view [here](https://github.com/CMSgov/github-actions-runner-aws/pull/104)
=> Fix 'update actions runner' workflow

.dockerfilelintrc, Dockerfile
Turns out Dockle is looking for the specific string `rm -rf /var/lib/apt/lists` after you run `apt update/install`.  dockerfilelint looks for `rm -rf /var/lib/apt/lists/*` (note the wildcard 🤦) so I chose Dockle and added a config file to disable that dockerfilelint rule
Testing:  Made sure the `build and push` workflow succeeded.
=> Update `Dockerfile` to satisfy Dockle

.github/actions/upload-asff/action.yml, .github/workflows/security.yml
We had commented out the SonarQube portion of the example security workflow since there was an [issue with the SAF](https://github.com/mitre/heimdall2/issues/3646) converter that is now [fixed](https://github.com/mitre/heimdall2/pull/3650).
While testing the fix I realized that I hadn't run SonarQube since we removed the AWS CLI from the runner image, so it took a little time to figure out[ the right way to do that](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).  In the process, I learned a bit about [adding things to the system PATH for GitHub runners](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path) that may come in handy in the future. 
I also made one small change to the composite action that …
=> Uncomment and test Sonarqube fix

.github/workflows/update-actions-runner.yml
I forgot to switch this workflow over to use my PAT when I made [this change](https://github.com/CMSgov/github-actions-runner-aws/pull/103) and deleted the robot secret. 
This reminds me that we really do need to get the new robot user set up.  I'll follow up with @yonassrobi about that.
Testing: I triggered the workflow to see that my token works and that removing the token argument to the Checkout action is OK (it is, the default `GITHUB_TOKEN` supplied to the workflow is sufficient for checking out)
=> Update token reference for 'Update Runner' workflow

.trivyignore
We don't have a choice about this since it's internal to the GitHub runner.   I'm hopeful that once we update the runner version we can revert this. 
Testing:  Trivy succeeded after the change
=> Add Node CVE to .trivyignore

.github/workflows/update-actions-runner.yml
The `update-actions-runner` workflow was failing to create pull releases. Turns out this is because I failed to notice when I made [this change](https://github.com/CMSgov/github-actions-runner-aws/pull/109) that it broke the `grep command` in the workflow by making it pick up all the lines with `ACTION_VERION` in them that I added to the Dockerfile.  This fixes that by making the `grep` command more specific.
Testing:  running the workflow from my feature branch created a PR successfully (I closed that PR since it didn't branch off of `main`).
=> Fix `grep` command

.github/workflows/docker-build.yml, Dockerfile, README.md, github-oidc/terraform/README.md, variables.tf
This is needed after the migration to `Enterprise-CMCS`.  I also had to update the GitHub runner version manually, otherwise, the `build-and-push` job would fail with a deprecation error.
Testing: none is needed other than seeing the automated CI succeed.
=> Update references to CMSgov repo

.dockleignore, .trivyignore, Dockerfile
This change:
- ignores one Trivy finding we can't control (CVE-2022-25881 for a node dependency in the runner)
- updates the `ubuntu` image in our `Dockerfile` to address a Trivy finding we can control (CVE-2023-0286)
- adds a `.dockleignore` with an entry for finding that we can't control (CIS-DI-0009, see the comment in that file for more info)
=> Fix Trivy and Dockle

.github/workflows/docker-build.yml, Dockerfile
I had to rework the `Dockerfile` a bit to get this to work.  Can't seem to find any documentation for it, but it looks like there were convenience wrappers around `groupadd` (`addgroup`)  and `useradd` (`adduser`) that were removed between versions.  So this change just calls them directly.  Also, I had to use a new group ID since `1000` is taken now.
=> Bump ubuntu to 23.04

github-oidc/terraform/variables.tf
This adds a second thumbprint to follow this update from GitHub: https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
Manual testing: 
- manually added the new thumbprint in the AWS console and ran the `docker-build.yml` workflow which uses the OIDC provider configured by this module.  The workflow ran successfully.
- updated the consumer in `mac-fc-infra` to use this branch and confirmed that no Terraform diff was shown
Note: the build and push job for this change will fail until https://github.com/Enterprise-CMCS/mac-fc-github-actions-runner-aws/pull/156 is merged.
=> Add GitHub OIDC server thumbprint

.github/workflows/docker-build.yml
This change updates the `docker-build` workflow to work with the new repo name (`github-actions-runner-aws` -> `mac-fc-github-actions-runner-aws`).  It also adds some error checking to the script that waits for the runner to be registered before proceeding to the runner test job. This fixes a bug where if curl exited with a non-zero code or the GitHub API returned a non-200 status, the waiter would still wait, rather than exiting with a non-zero code as it should. 
Manual testing:
- ran the workflow with the old repo name. This returned a `301` and thus triggered the new error-handling branch
- made sure the workflow ran successfully with the new repo name
=> Update repo name and fix waiter script

Dockerfile
Automated update from Github Actions Runner version 2.304.0 to version 2.306.0
Release Notes: https://github.com/actions/runner/releases/tag/v2.306.0
=> Update Actions Runner Version to 2.306.0

Dockerfile
Automated update from Github Actions Runner version 2.306.0 to version 2.307.0
Release Notes: https://github.com/actions/runner/releases/tag/v2.307.0
=> Update Actions Runner Version to 2.307.0

github-oidc/terraform/github-oidc.tf, github-oidc/terraform/variables.tf
https://jiraent.cms.gov/browse/CMCSMACD-1608
This PR allows the input policy that defines the IAM OIDC role permissions to be a JSON string and a path to a filename.
With this change, the policy can be specified as a policy document, that can be parameterized for different regions and accounts.
Tested:
I verified that with this change, the Kong smoke-test workflow can successfully run the credential action:
aws-actions/configure-aws-credentials@v3
and run all steps following the credential action
which means the change did not affect the current workflows
=> allow IAM OIDC role permissions policy to be json string

.github/workflows/build-and-push.yml, README.md, playwright.Dockerfile
This is a fix for https://github.com/Enterprise-CMCS/mac-fc-github-actions-runner-aws/pull/174. It pins the Playwright base image at 1.38.0 and renames the tag for the Playwright image so that it's clear what version is baked into the image. This is needed because if the version of the Playwright dependencies (in the image) and the Playwright runner are different, the tests won't run. I also updated the README to reflect this.
Tests:
- built the image locally
- built and pushed, and successfully ran tests on the image from the ProfessorMAC repo (which specifies 1.38.0)
=> Pin version of Playwright base image

github-oidc/terraform/versions.tf
Per best practices documented here https://developer.hashicorp.com/terraform/language/providers/requirements#best-practices-for-provider-versions, a module to be shared should specify the minimum acceptable version. Consumers of the module should specify the highest acceptable version. This protects the consumers from breaking updates to the consumed module.
This PR lowers the version of the AWS provider in the consumed module to `>= 4.0`.
=> change version to lowest acceptable version

github-oidc/terraform/github-oidc.tf
This fixes a constant diff I'm getting with respect to `managed_policy_arns` when `var.add_read_only_access` is false.
=> Fix managed_policy_arns constant diff.

github-actions-runner-terraform/container-definitions.tpl
It was erroneously updated in a previous commit.
Testing: successfully started a github runner in the professor-mac-dev account
=> Fix entrypoint

terraform/dev/account/terraform.tfstate, terraform/dev/account/versions.tf
https://jiraent.cms.gov/browse/CMCSMACD-1873
Set default tags for ecr and IAM identity provider, and role.
Tested:
successfully ran `terraform apply` 
then `terraform plan` showed No Changes
verified tags in IAM console and ECR console
=> add default tags to github-actions-runner IAM and ECR resources

latest.Dockerfile
https://jiraent.cms.gov/browse/CMCSMACD-1927
This PR reverts the self-hosted runner OS to ubuntu version 23.10 (from 24.04).
The reason is that 24.04 is a pre-released version, which confused dependabot.
Tested:
All automated tests passed.
=> revert ubuntu to 23.10

terraform/dev/account/ecr.tf
https://jiraent.cms.gov/browse/CMCSMACD-1862
for ECR repo:
enable scan on push
Note: tag must be set to MUTABLE (the default) since the repo tags each build with a SHA and `latest`
Tested:
Successfully ran `terraform apply`.
Saw in ECR console that playwright has 87 vulnerabilities (all MEDIUM and lower)
=> enable scan on push

.github/workflows/_docker-build.yml
We started seeing rate limit errors for Trivy when pulling the vulnerability DB from GHCR. It's a well-documented issue: https://github.com/aquasecurity/trivy-action/issues/389
This change adopts a recommended workaround for that issue: Trivy started[ pushing the DB to ECR](https://github.com/aquasecurity/trivy-db/pull/440), and switching to that source seems to have fixed the rate-limiting problem
Testing: ran the pipeline and it succeeded.
=> Fix Trivy rate limit error by pulling vulnerability DB from ECR

.github/workflows/_docker-build.yml, .github/workflows/build-and-push.yml, .github/workflows/pre-commit.yml, .trivyignore, .trivyignore-latest, .trivyignore-playwright, latest.Dockerfile
This housekeeping change:
- Bumps the Ubuntu base image version in the `latest.Dockerfile` to address CVE-2024-53103
- Splits the single trivyignore file into two, one for the `latest` image and one for the `playwright` image
- I did this so it's easier for consumers of the images to see what vulnerabilities we need to accept since they are baked in to the base images or software we use
- Installs Terraform in the pre-commit workflow since the `ubuntu-latest` GitHub runner [is now 24.04](https://github.com/actions/runner-images/issues/10636) and Terraform was "removed from the Ubuntu 24.04 image due to maintenance reasons."
Testing: 
- ran Trivy locally
- the build-push workflow ran successfully
=> Bump ubuntu base image to 25.04 for latest image; update trivyignores

latest.Dockerfile
Address https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#cis-di-0008 by removing all `setuid` and `setgid` permissions after installing packages.
Testing:
- ran Dockle locally and the finding wasn't found
- ran build workflow, it succeeded and the finding wasn't found
This is an esoteric corner of image security, so here's a background link as well as a summary and breakdown of the command (both courtesy of Claude): 
https://www.scaler.com/topics/special-permissions-in-linux/
> In Unix-like systems, every file has a set of permissions that control who can read, write, and execute it. But there's an additional layer - special permission bits called SUID (Set User ID) and SGID (Set Group ID). Think of these as temporary privilege escalation switches.
When the SUID bit is set …
=> Address Dockle finding

.github/workflows/_docker-build.yml, .github/workflows/build-and-push.yml, latest.Dockerfile, playwright.Dockerfile
T-MSIS consumes the image generated from `latest.Dockerfile`, and they scan for MEDIUM findings with Trivy. We should also scan at this level or else they will be complaining about findings that we don't see in our CI. But we don't want to scan for MEDIUM findings for the `playwright.Dockerfile` image for now, since we aren't free to upgrade the base image without a lot of work (since our CI is hardcoded to use Playwright 1.38.0 This change: 
- bumps `latest` to Ubuntu 25.10 to fix findings
- updates workflows to add scanning for MEDIUM findings for the latest image
Testing: 
- built and scanned the images locally
=> Scan and fix MEDIUM Trivy vulnerabilities for latest image

github-actions-runner-terraform/container-definitions.tpl
This change fixes a bug. Once in the past, GitHub deprecated our runner version and stopped accepting jobs from it (GitHub aggressively deprecates older runner versions, sometimes immediately when new versions are released). Our GitHub Actions runners broke even after we pushed a new runner image with the new runner version, because AWS ECS caches the old container image when we push updates to the same tag, requiring manual forced deployments to pick up changes. This is a feature called [versionConsistency](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#:~:text=Required%3A%20No-,versionConsistency,-Specifies%20whether%20Amazon) that can be disabled. We push to the same tag because we have external consumers of the image that pull it to get the …
=> Add version consistency to container definition

.dockerfilelintrc, .github/workflows/build-and-push.yml, .trivyignore-latest, latest.Dockerfile
https://jiraent.cms.gov/browse/CMCSMACD-4229
Added a cron schedule trigger to `build-and-push.yml` to run every Monday morning at 8am.
**Tested:**
- Rebuilt docker image and ran a trivy scan on it. No additional vulnerabilities were found.
=> [CMCSMACD-4229] add apt-get upgrade to dockerfile, add cron schedule to build-and-push workflow
